name: Master CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-test:
    name: Build & Test
    runs-on: ubuntu-latest
    if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"
    concurrency: ci-${{ github.ref }}

    steps:
    - uses: actions/checkout@v3
      with:
          fetch-depth: 0

    - name: Set up Python 3.10.5
      uses: actions/setup-python@v3
      with:
        python-version: "3.10.5"

    - name: Install dependencies
      run: pip install -r requirements.txt
    
    - name: Test
      run: pytest -v --cov=./ --cov-report xml

    - name: Fix code coverage path
      working-directory: ./
      run: sed -i 's@'$GITHUB_WORKSPACE'@/github/workspace/@g' coverage.xml

    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  deploy:
    name: Deploy
    needs: [ build-test ]
    runs-on: ubuntu-latest
    if: success() && github.ref == 'refs/heads/master'

    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY_1}}
          heroku_app_name: "switcher-slack-app"
          heroku_email: ${{secrets.HEROKU_EMAIL_1}}
  
  docker:
    name: Publish Docker Image
    needs: [ build-test ]
    runs-on: ubuntu-latest
    if: success() && github.ref == 'refs/heads/master'

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: trackerforce/switcher-slack-app:latest
