name: Master CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-test:
    name: Build & Test
    runs-on: ubuntu-latest
    if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"
    concurrency: ci-${{ github.ref }}

    steps:
    - uses: actions/checkout@v3
      with:
          fetch-depth: 0

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: pip install -r tests/requirements.txt
    
    - name: Test
      run: pytest -v --cov=./ --cov-report xml

    - name: Fix code coverage path
      working-directory: ./
      run: sed -i 's@'$GITHUB_WORKSPACE'@/github/workspace/@g' coverage.xml

    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@v1.8
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  
  docker:
    name: Publish Docker Image
    needs: [ build-test ]
    runs-on: ubuntu-latest
    if: success() && github.ref == 'refs/heads/master'

    outputs:
        digest: ${{ steps.docker_build.outputs.digest }}

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: trackerforce/switcher-slack-app:latest

  update-kustomize:
    name: Deploy
    needs: [ docker ]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: 'master'

      - name: Checkout Kustomize
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.ARGOCD_PAT }}
          repository: switcherapi/switcher-deployment
          ref: master

      - name: Set Image
        uses: stefanprodan/kube-tools@v1
        with:
          kubectl: 1.24.0
          kustomize: 4.5.4
          command: |
            cd switcher-slack-app/base
            echo RELEASE_TIME=`date` > environment-properties.env
            kustomize edit set image trackerforce/switcher-slack-app:latest=trackerforce/switcher-slack-app@${{ needs.docker.outputs.digest }}
            git config --global user.email "${{ github.actor }}@users.noreply.github.com"
            git config --global user.name "${{ github.actor }}"
            git add .
            git commit -m "[argocd] switcher-slack-app: ${{ needs.docker.outputs.digest }}"
            git push